GET http://localhost:5000/users

###
GET http://localhost:5000/users/3

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "judul" : "Senin",
    "desk" : "Membuat Reactjs"
}

###
PATCH http://localhost:5000/users/3
Content-Type: application/json

{
    "judul" : "Selasa",
    "desk" : "Membuat JavaScript"
}

###
DELETE http://localhost:5000/users/3